services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    environment:
      - VUE_APP_URL_BASE_API=${VUE_APP_URL_BASE_API}
      - N8N_EDITOR_BASE_URL=https://${N8N_HOST}
      - N8N_HOST=${N8N_HOST}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - WEBHOOK_URL=${WEBHOOK_URL}
      - DB_TYPE=postgres
      - DB_POSTGRES_HOST=pg-vector
      - DB_POSTGRES_PORT=5432
      - DB_POSTGRES_DATABASE=${POSTGRES_DB}
      - DB_POSTGRES_USER=${POSTGRES_USER}
      - DB_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    volumes:
      - ./data/n8n:/home/node/.n8n
    networks:
      - web
    depends_on:
      - pg-vector
  
  # n8n-backup:
  n8n-backup:
    image: alpine:latest
    container_name: n8n_backup
    volumes:
      - ./data/n8n:/data/n8n:ro
      - ./backups:/backups
      - ./back-up.sh:/back-up.sh
    entrypoint: ["/bin/sh", "-c"]
    command: >
      apk update &&
      apk add bash tar findutils &&
      chmod +x /back-up.sh &&
      /back-up.sh
    restart: unless-stopped


  pg-vector:
    image: ankane/pgvector
    container_name: pg-vector
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - web
    ports:
    - "5432:5432"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - web

networks:
  web:
    driver: bridge
